// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfe3aN66QkkSR4eoS9N3E89MNrcr38-J4',
    appId: '1:871216680825:web:703e03ab28dffbb95b69a8',
    messagingSenderId: '871216680825',
    projectId: 'flutter-demo-48216',
    authDomain: 'flutter-demo-48216.firebaseapp.com',
    storageBucket: 'flutter-demo-48216.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzyX7G2GOo7CeH4Xt47zeYrnPccc_XJQc',
    appId: '1:871216680825:android:7bfe4a130c42623b5b69a8',
    messagingSenderId: '871216680825',
    projectId: 'flutter-demo-48216',
    storageBucket: 'flutter-demo-48216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPx0QRaS3C0i_hYtlSnyT0tD268nGCO3U',
    appId: '1:871216680825:ios:20f1d8eba22749c35b69a8',
    messagingSenderId: '871216680825',
    projectId: 'flutter-demo-48216',
    storageBucket: 'flutter-demo-48216.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPx0QRaS3C0i_hYtlSnyT0tD268nGCO3U',
    appId: '1:871216680825:ios:20f1d8eba22749c35b69a8',
    messagingSenderId: '871216680825',
    projectId: 'flutter-demo-48216',
    storageBucket: 'flutter-demo-48216.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfe3aN66QkkSR4eoS9N3E89MNrcr38-J4',
    appId: '1:871216680825:web:f083853139c607175b69a8',
    messagingSenderId: '871216680825',
    projectId: 'flutter-demo-48216',
    authDomain: 'flutter-demo-48216.firebaseapp.com',
    storageBucket: 'flutter-demo-48216.firebasestorage.app',
  );
}
